CREATE TABLE IF NOT EXISTS `account_payment_orders` (
  `id` varchar(36) NOT NULL,
  `account_id` varchar(36) NOT NULL,
  `entitlement_code` varchar(64) NOT NULL,
  `source` varchar(32) NOT NULL DEFAULT 'web_pay',
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `duration_days` int NOT NULL DEFAULT 30,
  `amount_cents` int NOT NULL DEFAULT 0,
  `currency` varchar(16) NOT NULL DEFAULT 'CNY',
  `order_ref` varchar(128) NOT NULL,
  `provider_name` varchar(64) DEFAULT NULL,
  `provider_order_ref` varchar(128) DEFAULT NULL,
  `provider_payment_ref` varchar(128) DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `canceled_at` datetime DEFAULT NULL,
  `meta_json` json NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_account_payment_orders_order_ref` (`order_ref`),
  KEY `ix_account_payment_orders_account_id` (`account_id`),
  KEY `ix_account_payment_orders_entitlement_code` (`entitlement_code`),
  KEY `ix_account_payment_orders_source` (`source`),
  KEY `ix_account_payment_orders_status` (`status`),
  KEY `ix_account_payment_orders_provider_order_ref` (`provider_order_ref`),
  KEY `ix_account_payment_orders_provider_payment_ref` (`provider_payment_ref`),
  CONSTRAINT `fk_account_payment_orders_account_id`
    FOREIGN KEY (`account_id`) REFERENCES `portal_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
