PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
LoginGraceTime 20
MaxStartups 100:30:200
MaxSessions 50
UseDNS no
